#ifndef _INCLUDED_OPERAND_H_
#define _INCLUDED_OPERAND_H_

typedef enum _eSCRIPT_OPERAND
{
	SCRIPT_OPERAND_STORE,
	SCRIPT_OPERAND_RESTORE,
	SCRIPT_OPERAND_HEAP_STORE,
	SCRIPT_OPERAND_HEAP_RESTORE,
	SCRIPT_OPERAND_GLOBAL_STORE,
	SCRIPT_OPERAND_GLOBAL_RESTORE,
	SCRIPT_OPERAND_RESULT_MOVE,
	SCRIPT_OPERAND_PLUS,
	SCRIPT_OPERAND_MINUS,
	SCRIPT_OPERAND_MULTI,
	SCRIPT_OPERAND_DIVIDE,
	SCRIPT_OPERAND_MOD,
	SCRIPT_OPERAND_EQUAL,
	SCRIPT_OPERAND_NOT_EQUAL,
	SCRIPT_OPERAND_LESS,
	SCRIPT_OPERAND_LESS_EQUAL,
	SCRIPT_OPERAND_GREATER,
	SCRIPT_OPERAND_GREATER_EQUAL,
	SCRIPT_OPERAND_LOAD_CONST_INTEGER,
	SCRIPT_OPERAND_LOAD_CONST_FLOAT,
	SCRIPT_OPERAND_LOAD_CONST_STRING,
	SCRIPT_OPERAND_JUMP_IF_ZERO,
	SCRIPT_OPERAND_JUMP,
	SCRIPT_OPERAND_CALL_USER_FUNCTION,
	NUM_SCRIPT_OPERAND
} eSCRIPT_OPERAND;

typedef unsigned int script_operand;
typedef int script_int;
typedef double script_float;
#define SCRIPT_FLOAT_PRINT_FORMAT "%lf"
typedef int32 script_index;

#endif	// #ifndef _INCLUDED_OPERAND_H_
