#ifndef _INCLUDED_OPERAND_H_
#define _INCLUDED_OPERAND_H_

typedef enum _eSCRIPT_OPERAND
{
	SCRIPT_OPERAND_CONST_INTEGER,
	SCRIPT_OPERAND_CONST_STRING,
	SCRIPT_OPERAND_STORE,
	SCRIPT_OPERAND_RESTORE,
	SCRIPT_OPERAND_HEAP_STORE,
	SCRIPT_OPERAND_HEAP_RESTORE,
	SCRIPT_OPERAND_GLOBAL_STORE,
	SCRIPT_OPERAND_GLOBAL_RESTORE,
	SCRIPT_OPERAND_RESULT_MOVE,
	SCRIPT_OPERAND_PLUS,
	SCRIPT_OPERAND_MINUS,
	SCRIPT_OPERAND_MULTI,
	SCRIPT_OPERAND_DEVIDE,
	SCRIPT_OPERAND_MOD,
	SCRIPT_OPERAND_EQUAL,
	SCRIPT_OPERAND_LESS,
	SCRIPT_OPERAND_LESS_EQUAL,
	SCRIPT_OPERAND_MORE,
	SCRIPT_OPERAND_MORE_EQUAL,
	NUM_SCRIPT_OPERAND
} eSCRIPT_OPERAND;

#endif	// #ifndef _INCLUDED_OPERAND_H_
